
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen w-full text-white bg-linear-to-t from-gray-500 to-gray-700 flex flex-col items-center justify-center"
      >
        {children}
      </body>
    </html>
  );
}
